// Generated by dust (version 0.15.1) - do not edit
#include <cpp11.hpp>

[[cpp11::register]]
cpp11::sexp dust_seirhdage_gpu_info();
[[cpp11::register]]
SEXP dust_cpu_seirhdage_alloc(cpp11::list r_pars, bool pars_multi, cpp11::sexp r_time,
                         cpp11::sexp r_n_particles, int n_threads,
                         cpp11::sexp r_seed, bool deterministic,
                         cpp11::sexp gpu_config, cpp11::sexp ode_control);

[[cpp11::register]]
cpp11::sexp dust_cpu_seirhdage_capabilities();

[[cpp11::register]]
SEXP dust_cpu_seirhdage_run(SEXP ptr, cpp11::sexp r_time_end);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_simulate(SEXP ptr, cpp11::sexp time_end);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_run_adjoint(SEXP ptr);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_set_index(SEXP ptr, cpp11::sexp r_index);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_update_state(SEXP ptr, SEXP r_pars, SEXP r_state,
                                           SEXP r_time, SEXP r_set_initial_state,
                                           SEXP index, SEXP reset_step_size);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_state(SEXP ptr, SEXP r_index);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_time(SEXP ptr);

[[cpp11::register]]
void dust_cpu_seirhdage_reorder(SEXP ptr, cpp11::sexp r_index);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_resample(SEXP ptr, cpp11::doubles r_weights);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_rng_state(SEXP ptr, bool first_only, bool last_only);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_set_rng_state(SEXP ptr, cpp11::raws rng_state);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_set_data(SEXP ptr, cpp11::list data, bool shared);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_compare_data(SEXP ptr);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_filter(SEXP ptr, SEXP time_end,
                                     bool save_trajectories,
                                     cpp11::sexp time_snapshot,
                                     cpp11::sexp min_log_likelihood);

[[cpp11::register]]
void dust_cpu_seirhdage_set_n_threads(SEXP ptr, int n_threads);

[[cpp11::register]]
int dust_cpu_seirhdage_n_state(SEXP ptr);

[[cpp11::register]]
void dust_cpu_seirhdage_set_stochastic_schedule(SEXP ptr, SEXP time);

[[cpp11::register]]
SEXP dust_cpu_seirhdage_ode_statistics(SEXP ptr);
#include <dust/r/dust.hpp>

// Generated by odin.dust (version 0.3.10) - do not edit
template <typename real_type, typename container>
__host__ __device__ real_type odin_sum1(const container x, size_t from, size_t to);
template <typename real_type, typename container>
__host__ __device__ real_type odin_sum2(const container x, int from_i, int to_i, int from_j, int to_j, int dim_x_1);
template <typename real_type, typename T, typename U>
__host__ __device__ real_type fintdiv(T x, U y) {
  return std::floor(x / y);
}

template <typename real_type, typename T, typename U>
__host__ __device__ real_type fmodr(T x, U y) {
  real_type tmp = std::fmod(static_cast<real_type>(x),
                            static_cast<real_type>(y));
  if (tmp * y < 0) {
    tmp += y;
  }
  return tmp;
}

// These exist to support the model on the gpu, as in C++14 std::min
// and std::max are constexpr and error without --expt-relaxed-constexpr
template <typename T>
__host__ __device__ T odin_min(T x, T y) {
  return x < y ? x : y;
}

template <typename T>
__host__ __device__ T odin_max(T x, T y) {
  return x > y ? x : y;
}

template <typename T>
__host__ __device__ T odin_sign(T x) {
  return (x > 0) ? 1 : ((x < 0) ? -1 : 0);
}
// [[dust::class(seirhdage)]]
// [[dust::time_type(discrete)]]
// [[dust::param(dt, has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(E_ini, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(I_ini, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(m, has_default = FALSE, default_value = NULL, rank = 2, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(n_age, has_default = FALSE, default_value = NULL, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(p_C, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(p_D, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(p_G, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(p_H, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(S_ini, has_default = FALSE, default_value = NULL, rank = 1, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(beta, has_default = TRUE, default_value = 0.03, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(gamma_A, has_default = TRUE, default_value = 0.2, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(gamma_C, has_default = TRUE, default_value = 0.4, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(gamma_G, has_default = TRUE, default_value = list("/", 1L, 3L), rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(gamma_H, has_default = TRUE, default_value = 0.1, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(gamma_P, has_default = TRUE, default_value = 0.4, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(sigma, has_default = TRUE, default_value = 0.5, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
// [[dust::param(theta_A, has_default = TRUE, default_value = 0.5, rank = 0, min = -Inf, max = Inf, integer = FALSE)]]
class seirhdage {
public:
  using real_type = double;
  using rng_state_type = dust::random::generator<real_type>;
  using data_type = dust::no_data;
  struct shared_type {
    real_type beta;
    int dim_D;
    int dim_E;
    int dim_E_ini;
    int dim_G;
    int dim_H;
    int dim_I_A;
    int dim_I_C;
    int dim_I_ini;
    int dim_I_P;
    int dim_lambda;
    int dim_m;
    int dim_m_1;
    int dim_m_2;
    int dim_n_EI;
    int dim_n_EI_A;
    int dim_n_EI_P;
    int dim_n_GD;
    int dim_n_HD;
    int dim_n_HR;
    int dim_n_Hx;
    int dim_n_I_AR;
    int dim_n_I_CG;
    int dim_n_I_CH;
    int dim_n_I_CHG;
    int dim_n_I_CR;
    int dim_n_I_Cx;
    int dim_n_I_PI_C;
    int dim_n_SE;
    int dim_N_tot;
    int dim_p_C;
    int dim_p_D;
    int dim_p_G;
    int dim_p_H;
    int dim_p_SE;
    int dim_R;
    int dim_S;
    int dim_s_ij;
    int dim_s_ij_1;
    int dim_s_ij_2;
    int dim_S_ini;
    real_type dt;
    std::vector<real_type> E_ini;
    real_type gamma_A;
    real_type gamma_C;
    real_type gamma_G;
    real_type gamma_H;
    real_type gamma_P;
    std::vector<real_type> I_ini;
    std::vector<real_type> initial_D;
    real_type initial_D_inc;
    real_type initial_D_inc_0_39;
    real_type initial_D_inc_40_49;
    real_type initial_D_inc_50_59;
    real_type initial_D_inc_60_69;
    real_type initial_D_inc_70_plus;
    std::vector<real_type> initial_E;
    std::vector<real_type> initial_G;
    std::vector<real_type> initial_H;
    real_type initial_H_inc;
    real_type initial_H_inc_0_39;
    real_type initial_H_inc_40_49;
    real_type initial_H_inc_50_59;
    real_type initial_H_inc_60_69;
    real_type initial_H_inc_70_plus;
    std::vector<real_type> initial_I_A;
    std::vector<real_type> initial_I_C;
    std::vector<real_type> initial_I_P;
    std::vector<real_type> initial_N_tot;
    std::vector<real_type> initial_R;
    std::vector<real_type> initial_S;
    real_type initial_time;
    std::vector<real_type> m;
    int n_age;
    int offset_variable_D;
    int offset_variable_E;
    int offset_variable_G;
    int offset_variable_H;
    int offset_variable_I_A;
    int offset_variable_I_C;
    int offset_variable_I_P;
    int offset_variable_N_tot;
    int offset_variable_R;
    std::vector<real_type> p_C;
    std::vector<real_type> p_D;
    real_type p_EI;
    std::vector<real_type> p_G;
    real_type p_GD;
    std::vector<real_type> p_H;
    real_type p_Hx;
    real_type p_I_AR;
    real_type p_I_Cx;
    real_type p_I_PI_C;
    std::vector<real_type> S_ini;
    real_type sigma;
    real_type steps_per_day;
    real_type theta_A;
  };
  struct internal_type {
    std::vector<real_type> lambda;
    std::vector<real_type> n_EI;
    std::vector<real_type> n_EI_A;
    std::vector<real_type> n_EI_P;
    std::vector<real_type> n_GD;
    std::vector<real_type> n_HD;
    std::vector<real_type> n_HR;
    std::vector<real_type> n_Hx;
    std::vector<real_type> n_I_AR;
    std::vector<real_type> n_I_CG;
    std::vector<real_type> n_I_CH;
    std::vector<real_type> n_I_CHG;
    std::vector<real_type> n_I_CR;
    std::vector<real_type> n_I_Cx;
    std::vector<real_type> n_I_PI_C;
    std::vector<real_type> n_SE;
    std::vector<real_type> p_SE;
    std::vector<real_type> s_ij;
  };
  seirhdage(const dust::pars_type<seirhdage>& pars) :
    shared(pars.shared), internal(pars.internal) {
  }
  size_t size() const {
    return shared->dim_D + shared->dim_E + shared->dim_G + shared->dim_H + shared->dim_I_A + shared->dim_I_C + shared->dim_I_P + shared->dim_N_tot + shared->dim_R + shared->dim_S + 13;
  }
  std::vector<real_type> initial(size_t step, rng_state_type& rng_state) {
    std::vector<real_type> state(shared->dim_D + shared->dim_E + shared->dim_G + shared->dim_H + shared->dim_I_A + shared->dim_I_C + shared->dim_I_P + shared->dim_N_tot + shared->dim_R + shared->dim_S + 13);
    state[0] = shared->initial_time;
    state[1] = shared->initial_H_inc;
    state[2] = shared->initial_D_inc;
    state[3] = shared->initial_H_inc_0_39;
    state[4] = shared->initial_H_inc_40_49;
    state[5] = shared->initial_H_inc_50_59;
    state[6] = shared->initial_H_inc_60_69;
    state[7] = shared->initial_H_inc_70_plus;
    state[8] = shared->initial_D_inc_0_39;
    state[9] = shared->initial_D_inc_40_49;
    state[10] = shared->initial_D_inc_50_59;
    state[11] = shared->initial_D_inc_60_69;
    state[12] = shared->initial_D_inc_70_plus;
    std::copy(shared->initial_S.begin(), shared->initial_S.end(), state.begin() + 13);
    std::copy(shared->initial_E.begin(), shared->initial_E.end(), state.begin() + shared->offset_variable_E);
    std::copy(shared->initial_I_P.begin(), shared->initial_I_P.end(), state.begin() + shared->offset_variable_I_P);
    std::copy(shared->initial_I_A.begin(), shared->initial_I_A.end(), state.begin() + shared->offset_variable_I_A);
    std::copy(shared->initial_I_C.begin(), shared->initial_I_C.end(), state.begin() + shared->offset_variable_I_C);
    std::copy(shared->initial_R.begin(), shared->initial_R.end(), state.begin() + shared->offset_variable_R);
    std::copy(shared->initial_H.begin(), shared->initial_H.end(), state.begin() + shared->offset_variable_H);
    std::copy(shared->initial_G.begin(), shared->initial_G.end(), state.begin() + shared->offset_variable_G);
    std::copy(shared->initial_D.begin(), shared->initial_D.end(), state.begin() + shared->offset_variable_D);
    std::copy(shared->initial_N_tot.begin(), shared->initial_N_tot.end(), state.begin() + shared->offset_variable_N_tot);
    return state;
  }
  void update(size_t step, const real_type * state, rng_state_type& rng_state, real_type * state_next) {
    const real_type * S = state + 13;
    const real_type * E = state + shared->offset_variable_E;
    const real_type * I_P = state + shared->offset_variable_I_P;
    const real_type * I_A = state + shared->offset_variable_I_A;
    const real_type * I_C = state + shared->offset_variable_I_C;
    const real_type * R = state + shared->offset_variable_R;
    const real_type * H = state + shared->offset_variable_H;
    const real_type * G = state + shared->offset_variable_G;
    const real_type * D = state + shared->offset_variable_D;
    const real_type H_inc = state[1];
    const real_type D_inc = state[2];
    const real_type H_inc_0_39 = state[3];
    const real_type H_inc_40_49 = state[4];
    const real_type H_inc_50_59 = state[5];
    const real_type H_inc_60_69 = state[6];
    const real_type H_inc_70_plus = state[7];
    const real_type D_inc_0_39 = state[8];
    const real_type D_inc_40_49 = state[9];
    const real_type D_inc_50_59 = state[10];
    const real_type D_inc_60_69 = state[11];
    const real_type D_inc_70_plus = state[12];
    state_next[0] = (step + 1) * shared->dt;
    for (int i = 1; i <= shared->dim_N_tot; ++i) {
      state_next[shared->offset_variable_N_tot + i - 1] = S[i - 1] + E[i - 1] + I_P[i - 1] + I_A[i - 1] + I_C[i - 1] + R[i - 1] + H[i - 1] + G[i - 1] + D[i - 1];
    }
    for (int i = 1; i <= shared->dim_n_EI; ++i) {
      internal.n_EI[i - 1] = dust::random::binomial<real_type>(rng_state, E[i - 1], shared->p_EI);
    }
    for (int i = 1; i <= shared->dim_n_GD; ++i) {
      internal.n_GD[i - 1] = dust::random::binomial<real_type>(rng_state, G[i - 1], shared->p_GD);
    }
    for (int i = 1; i <= shared->dim_n_Hx; ++i) {
      internal.n_Hx[i - 1] = dust::random::binomial<real_type>(rng_state, H[i - 1], shared->p_Hx);
    }
    for (int i = 1; i <= shared->dim_n_I_AR; ++i) {
      internal.n_I_AR[i - 1] = dust::random::binomial<real_type>(rng_state, I_A[i - 1], shared->p_I_AR);
    }
    for (int i = 1; i <= shared->dim_n_I_Cx; ++i) {
      internal.n_I_Cx[i - 1] = dust::random::binomial<real_type>(rng_state, I_C[i - 1], shared->p_I_Cx);
    }
    for (int i = 1; i <= shared->dim_n_I_PI_C; ++i) {
      internal.n_I_PI_C[i - 1] = dust::random::binomial<real_type>(rng_state, I_P[i - 1], shared->p_I_PI_C);
    }
    for (int i = 1; i <= shared->dim_n_EI_P; ++i) {
      internal.n_EI_P[i - 1] = dust::random::binomial<real_type>(rng_state, internal.n_EI[i - 1], shared->p_C[i - 1]);
    }
    for (int i = 1; i <= shared->dim_n_HD; ++i) {
      internal.n_HD[i - 1] = dust::random::binomial<real_type>(rng_state, internal.n_Hx[i - 1], shared->p_D[i - 1]);
    }
    for (int i = 1; i <= shared->dim_n_I_CR; ++i) {
      internal.n_I_CR[i - 1] = dust::random::binomial<real_type>(rng_state, internal.n_I_Cx[i - 1], 1 - shared->p_H[i - 1]);
    }
    for (int i = 1; i <= shared->dim_s_ij_1; ++i) {
      for (int j = 1; j <= shared->dim_s_ij_2; ++j) {
        internal.s_ij[i - 1 + shared->dim_s_ij_1 * (j - 1)] = shared->m[shared->dim_m_1 * (j - 1) + i - 1] * (shared->theta_A * I_A[i - 1] + I_P[i - 1] + I_C[i - 1]);
      }
    }
    for (int i = 1; i <= shared->dim_lambda; ++i) {
      internal.lambda[i - 1] = shared->beta * odin_sum2<real_type>(internal.s_ij.data(), 0, shared->dim_s_ij_1, i - 1, i, shared->dim_s_ij_1);
    }
    for (int i = 1; i <= shared->dim_n_EI_A; ++i) {
      internal.n_EI_A[i - 1] = internal.n_EI[i - 1] - internal.n_EI_P[i - 1];
    }
    for (int i = 1; i <= shared->dim_n_HR; ++i) {
      internal.n_HR[i - 1] = internal.n_Hx[i - 1] - internal.n_HD[i - 1];
    }
    for (int i = 1; i <= shared->dim_n_I_CHG; ++i) {
      internal.n_I_CHG[i - 1] = internal.n_I_Cx[i - 1] - internal.n_I_CR[i - 1];
    }
    for (int i = 1; i <= shared->dim_D; ++i) {
      state_next[shared->offset_variable_D + i - 1] = D[i - 1] + internal.n_HD[i - 1] + internal.n_GD[i - 1];
    }
    state_next[2] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? odin_sum1<real_type>(internal.n_HD.data(), 0, shared->dim_n_HD) : D_inc + odin_sum1<real_type>(internal.n_HD.data(), 0, shared->dim_n_HD));
    state_next[8] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? odin_sum1<real_type>(internal.n_HD.data(), 0, 4) : D_inc_0_39 + odin_sum1<real_type>(internal.n_HD.data(), 0, 4));
    state_next[9] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? internal.n_HD[4] : D_inc_40_49 + internal.n_HD[4]);
    state_next[10] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? internal.n_HD[5] : D_inc_50_59 + internal.n_HD[5]);
    state_next[11] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? internal.n_HD[6] : D_inc_60_69 + internal.n_HD[6]);
    state_next[12] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? internal.n_HD[7] : D_inc_70_plus + internal.n_HD[7]);
    for (int i = 1; i <= shared->dim_I_P; ++i) {
      state_next[shared->offset_variable_I_P + i - 1] = I_P[i - 1] + internal.n_EI_P[i - 1] - internal.n_I_PI_C[i - 1];
    }
    for (int i = 1; i <= shared->dim_n_I_CH; ++i) {
      internal.n_I_CH[i - 1] = dust::random::binomial<real_type>(rng_state, internal.n_I_CHG[i - 1], 1 - shared->p_G[i - 1]);
    }
    for (int i = 1; i <= shared->dim_p_SE; ++i) {
      internal.p_SE[i - 1] = 1 - dust::math::exp(- internal.lambda[i - 1] * shared->dt);
    }
    for (int i = 1; i <= shared->dim_I_A; ++i) {
      state_next[shared->offset_variable_I_A + i - 1] = I_A[i - 1] + internal.n_EI_A[i - 1] - internal.n_I_AR[i - 1];
    }
    for (int i = 1; i <= shared->dim_R; ++i) {
      state_next[shared->offset_variable_R + i - 1] = R[i - 1] + internal.n_I_AR[i - 1] + internal.n_I_CR[i - 1] + internal.n_HR[i - 1];
    }
    for (int i = 1; i <= shared->dim_n_I_CG; ++i) {
      internal.n_I_CG[i - 1] = internal.n_I_CHG[i - 1] - internal.n_I_CH[i - 1];
    }
    for (int i = 1; i <= shared->dim_n_SE; ++i) {
      internal.n_SE[i - 1] = dust::random::binomial<real_type>(rng_state, S[i - 1], internal.p_SE[i - 1]);
    }
    for (int i = 1; i <= shared->dim_H; ++i) {
      state_next[shared->offset_variable_H + i - 1] = H[i - 1] + internal.n_I_CH[i - 1] - internal.n_HR[i - 1] - internal.n_HD[i - 1];
    }
    state_next[1] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? odin_sum1<real_type>(internal.n_I_CH.data(), 0, shared->dim_n_I_CH) : H_inc + odin_sum1<real_type>(internal.n_I_CH.data(), 0, shared->dim_n_I_CH));
    state_next[3] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? odin_sum1<real_type>(internal.n_I_CH.data(), 0, 4) : H_inc_0_39 + odin_sum1<real_type>(internal.n_I_CH.data(), 0, 4));
    state_next[4] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? internal.n_I_CH[4] : H_inc_40_49 + internal.n_I_CH[4]);
    state_next[5] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? internal.n_I_CH[5] : H_inc_50_59 + internal.n_I_CH[5]);
    state_next[6] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? internal.n_I_CH[6] : H_inc_60_69 + internal.n_I_CH[6]);
    state_next[7] = (fmodr<real_type>(step, shared->steps_per_day) == 0 ? internal.n_I_CH[7] : H_inc_70_plus + internal.n_I_CH[7]);
    for (int i = 1; i <= shared->dim_E; ++i) {
      state_next[shared->offset_variable_E + i - 1] = E[i - 1] + internal.n_SE[i - 1] - internal.n_EI[i - 1];
    }
    for (int i = 1; i <= shared->dim_G; ++i) {
      state_next[shared->offset_variable_G + i - 1] = G[i - 1] + internal.n_I_CG[i - 1] - internal.n_GD[i - 1];
    }
    for (int i = 1; i <= shared->dim_I_C; ++i) {
      state_next[shared->offset_variable_I_C + i - 1] = I_C[i - 1] + internal.n_I_PI_C[i - 1] - internal.n_I_CR[i - 1] - internal.n_I_CH[i - 1] - internal.n_I_CG[i - 1];
    }
    for (int i = 1; i <= shared->dim_S; ++i) {
      state_next[13 + i - 1] = S[i - 1] - internal.n_SE[i - 1];
    }
  }
private:
  std::shared_ptr<const shared_type> shared;
  internal_type internal;
};
template <typename real_type, typename container>
__host__ __device__ real_type odin_sum2(const container x, int from_i, int to_i, int from_j, int to_j, int dim_x_1) {
  real_type tot = 0.0;
  for (int j = from_j; j < to_j; ++j) {
    int jj = j * dim_x_1;
    for (int i = from_i; i < to_i; ++i) {
      tot += x[i + jj];
    }
  }
  return tot;
}
#include <array>
#include <cpp11/R.hpp>
#include <cpp11/sexp.hpp>
#include <cpp11/doubles.hpp>
#include <cpp11/integers.hpp>
#include <cpp11/list.hpp>
#include <cpp11/strings.hpp>
#include <memory>
#include <vector>

template <typename T>
inline bool is_na(T x);

template <>
inline bool is_na(int x) {
  return x == NA_INTEGER;
}

template <>
inline bool is_na(double x) {
  return ISNA(x);
}

inline size_t object_length(cpp11::sexp x) {
  return ::Rf_xlength(x);
}

template <typename T>
void user_check_value(T value, const char *name, T min, T max) {
  if (is_na(value)) {
    cpp11::stop("'%s' must not be NA", name);
  }
  if (!is_na(min) && value < min) {
    cpp11::stop("Expected '%s' to be at least %g", name, (double) min);
  }
  if (!is_na(max) && value > max) {
    cpp11::stop("Expected '%s' to be at most %g", name, (double) max);
  }
}

template <typename T>
void user_check_array_value(const std::vector<T>& value, const char *name,
                            T min, T max) {
  for (auto& x : value) {
    user_check_value(x, name, min, max);
  }
}

inline size_t user_get_array_rank(cpp11::sexp x) {
  if (!::Rf_isArray(x)) {
    return 1;
  } else {
    cpp11::integers dim = cpp11::as_cpp<cpp11::integers>(x.attr("dim"));
    return dim.size();
  }
}

template <size_t N>
void user_check_array_rank(cpp11::sexp x, const char *name) {
  size_t rank = user_get_array_rank(x);
  if (rank != N) {
    if (N == 1) {
      cpp11::stop("Expected a vector for '%s'", name);
    } else if (N == 2) {
      cpp11::stop("Expected a matrix for '%s'", name);
    } else {
      cpp11::stop("Expected an array of rank %d for '%s'", N, name);
    }
  }
}

template <size_t N>
void user_check_array_dim(cpp11::sexp x, const char *name,
                          const std::array<int, N>& dim_expected) {
  cpp11::integers dim = cpp11::as_cpp<cpp11::integers>(x.attr("dim"));
  for (size_t i = 0; i < N; ++i) {
    if (dim[(int)i] != dim_expected[i]) {
      Rf_error("Incorrect size of dimension %d of '%s' (expected %d)",
               i + 1, name, dim_expected[i]);
    }
  }
}

template <>
inline void user_check_array_dim<1>(cpp11::sexp x, const char *name,
                                    const std::array<int, 1>& dim_expected) {
  if ((int)object_length(x) != dim_expected[0]) {
    cpp11::stop("Expected length %d value for '%s'", dim_expected[0], name);
  }
}

template <size_t N>
void user_set_array_dim(cpp11::sexp x, const char *name,
                        std::array<int, N>& dim) {
  cpp11::integers dim_given = cpp11::as_cpp<cpp11::integers>(x.attr("dim"));
  std::copy(dim_given.begin(), dim_given.end(), dim.begin());
}

template <>
inline void user_set_array_dim<1>(cpp11::sexp x, const char *name,
                                  std::array<int, 1>& dim) {
  dim[0] = object_length(x);
}

template <typename T>
T user_get_scalar(cpp11::list user, const char *name,
                  const T previous, T min, T max) {
  T ret = previous;
  cpp11::sexp x = user[name];
  if (x != R_NilValue) {
    if (object_length(x) != 1) {
      cpp11::stop("Expected a scalar numeric for '%s'", name);
    }
    // TODO: when we're getting out an integer this is a bit too relaxed
    if (TYPEOF(x) == REALSXP) {
      ret = cpp11::as_cpp<T>(x);
    } else if (TYPEOF(x) == INTSXP) {
      ret = cpp11::as_cpp<T>(x);
    } else {
      cpp11::stop("Expected a numeric value for %s", name);
    }
  }

  if (is_na(ret)) {
    cpp11::stop("Expected a value for '%s'", name);
  }
  user_check_value<T>(ret, name, min, max);
  return ret;
}

template <>
inline float user_get_scalar<float>(cpp11::list user, const char *name,
                                    const float previous, float min, float max) {
  double value = user_get_scalar<double>(user, name, previous, min, max);
  return static_cast<float>(value);
}

template <typename T>
std::vector<T> user_get_array_value(cpp11::sexp x, const char * name,
                                    T min, T max) {
  std::vector<T> ret = cpp11::as_cpp<std::vector<T>>(x);
  user_check_array_value<T>(ret, name, min, max);
  return ret;
}

template <typename T, size_t N>
std::vector<T> user_get_array_fixed(cpp11::list user, const char *name,
                                    const std::vector<T> previous,
                                    const std::array<int, N>& dim,
                                    T min, T max) {
  cpp11::sexp x = user[name];
  if (x == R_NilValue) {
    if (previous.size() == 0) {
      cpp11::stop("Expected a value for '%s'", name);
    }
    return previous;
  }

  user_check_array_rank<N>(x, name);
  user_check_array_dim<N>(x, name, dim);

  return user_get_array_value<T>(x, name, min, max);
}

template <typename T, size_t N>
std::vector<T> user_get_array_variable(cpp11::list user, const char *name,
                                       std::vector<T> previous,
                                       std::array<int, N>& dim,
                                       T min, T max) {
  cpp11::sexp x = user[name];
  if (x == R_NilValue) {
    if (previous.size() == 0) {
      cpp11::stop("Expected a value for '%s'", name);
    }
    return previous;
  }

  user_check_array_rank<N>(x, name);
  user_set_array_dim<N>(x, name, dim);

  return user_get_array_value<T>(x, name, min, max);
}

template <>
inline std::vector<float> user_get_array_value(cpp11::sexp x, const char * name,
                                               float min, float max) {
  // NOTE: possible under/overflow here for min/max because we've
  // downcast this.
  std::vector<double> value = user_get_array_value<double>(x, name, min, max);
  std::vector<float> ret(value.size());
  std::copy(value.begin(), value.end(), ret.begin());
  return ret;
}

// This is sum with inclusive "from", exclusive "to", following the
// same function in odin
template <typename real_type, typename container>
__host__ __device__
real_type odin_sum1(const container x, size_t from, size_t to) {
  real_type tot = 0.0;
  for (size_t i = from; i < to; ++i) {
    tot += x[i];
  }
  return tot;
}

inline cpp11::writable::integers integer_sequence(size_t from, size_t len) {
  cpp11::writable::integers ret(len);
  int* data = INTEGER(ret);
  for (size_t i = 0, j = from; i < len; ++i, ++j) {
    data[i] = j;
  }
  return ret;
}
namespace dust {
template<>
dust::pars_type<seirhdage> dust_pars<seirhdage>(cpp11::list user) {
  using real_type = typename seirhdage::real_type;
  auto shared = std::make_shared<seirhdage::shared_type>();
  seirhdage::internal_type internal;
  shared->initial_D_inc = 0;
  shared->initial_D_inc_0_39 = 0;
  shared->initial_D_inc_40_49 = 0;
  shared->initial_D_inc_50_59 = 0;
  shared->initial_D_inc_60_69 = 0;
  shared->initial_D_inc_70_plus = 0;
  shared->initial_H_inc = 0;
  shared->initial_H_inc_0_39 = 0;
  shared->initial_H_inc_40_49 = 0;
  shared->initial_H_inc_50_59 = 0;
  shared->initial_H_inc_60_69 = 0;
  shared->initial_H_inc_70_plus = 0;
  shared->initial_time = 0;
  shared->dt = NA_REAL;
  shared->n_age = NA_INTEGER;
  shared->beta = static_cast<real_type>(0.029999999999999999);
  shared->gamma_A = static_cast<real_type>(0.20000000000000001);
  shared->gamma_C = static_cast<real_type>(0.40000000000000002);
  shared->gamma_G = 1 / (real_type) 3;
  shared->gamma_H = static_cast<real_type>(0.10000000000000001);
  shared->gamma_P = static_cast<real_type>(0.40000000000000002);
  shared->sigma = static_cast<real_type>(0.5);
  shared->theta_A = static_cast<real_type>(0.5);
  shared->beta = user_get_scalar<real_type>(user, "beta", shared->beta, NA_REAL, NA_REAL);
  shared->dt = user_get_scalar<real_type>(user, "dt", shared->dt, NA_REAL, NA_REAL);
  shared->gamma_A = user_get_scalar<real_type>(user, "gamma_A", shared->gamma_A, NA_REAL, NA_REAL);
  shared->gamma_C = user_get_scalar<real_type>(user, "gamma_C", shared->gamma_C, NA_REAL, NA_REAL);
  shared->gamma_G = user_get_scalar<real_type>(user, "gamma_G", shared->gamma_G, NA_REAL, NA_REAL);
  shared->gamma_H = user_get_scalar<real_type>(user, "gamma_H", shared->gamma_H, NA_REAL, NA_REAL);
  shared->gamma_P = user_get_scalar<real_type>(user, "gamma_P", shared->gamma_P, NA_REAL, NA_REAL);
  shared->n_age = user_get_scalar<int>(user, "n_age", shared->n_age, NA_INTEGER, NA_INTEGER);
  shared->sigma = user_get_scalar<real_type>(user, "sigma", shared->sigma, NA_REAL, NA_REAL);
  shared->theta_A = user_get_scalar<real_type>(user, "theta_A", shared->theta_A, NA_REAL, NA_REAL);
  shared->dim_D = shared->n_age;
  shared->dim_E = shared->n_age;
  shared->dim_E_ini = shared->n_age;
  shared->dim_G = shared->n_age;
  shared->dim_H = shared->n_age;
  shared->dim_I_A = shared->n_age;
  shared->dim_I_C = shared->n_age;
  shared->dim_I_ini = shared->n_age;
  shared->dim_I_P = shared->n_age;
  shared->dim_lambda = shared->n_age;
  shared->dim_m_1 = shared->n_age;
  shared->dim_m_2 = shared->n_age;
  shared->dim_n_EI = shared->n_age;
  shared->dim_n_EI_A = shared->n_age;
  shared->dim_n_EI_P = shared->n_age;
  shared->dim_n_GD = shared->n_age;
  shared->dim_n_HD = shared->n_age;
  shared->dim_n_HR = shared->n_age;
  shared->dim_n_Hx = shared->n_age;
  shared->dim_n_I_AR = shared->n_age;
  shared->dim_n_I_CG = shared->n_age;
  shared->dim_n_I_CH = shared->n_age;
  shared->dim_n_I_CHG = shared->n_age;
  shared->dim_n_I_CR = shared->n_age;
  shared->dim_n_I_Cx = shared->n_age;
  shared->dim_n_I_PI_C = shared->n_age;
  shared->dim_n_SE = shared->n_age;
  shared->dim_N_tot = shared->n_age;
  shared->dim_p_C = shared->n_age;
  shared->dim_p_D = shared->n_age;
  shared->dim_p_G = shared->n_age;
  shared->dim_p_H = shared->n_age;
  shared->dim_p_SE = shared->n_age;
  shared->dim_R = shared->n_age;
  shared->dim_S = shared->n_age;
  shared->dim_s_ij_1 = shared->n_age;
  shared->dim_s_ij_2 = shared->n_age;
  shared->dim_S_ini = shared->n_age;
  shared->p_EI = 1 - dust::math::exp(- shared->sigma * shared->dt);
  shared->p_GD = 1 - dust::math::exp(- shared->gamma_G * shared->dt);
  shared->p_Hx = 1 - dust::math::exp(- shared->gamma_H * shared->dt);
  shared->p_I_AR = 1 - dust::math::exp(- shared->gamma_A * shared->dt);
  shared->p_I_Cx = 1 - dust::math::exp(- shared->gamma_C * shared->dt);
  shared->p_I_PI_C = 1 - dust::math::exp(- shared->gamma_P * shared->dt);
  shared->steps_per_day = 1 / (real_type) shared->dt;
  shared->initial_D = std::vector<real_type>(shared->dim_D);
  shared->initial_E = std::vector<real_type>(shared->dim_E);
  shared->initial_G = std::vector<real_type>(shared->dim_G);
  shared->initial_H = std::vector<real_type>(shared->dim_H);
  shared->initial_I_A = std::vector<real_type>(shared->dim_I_A);
  shared->initial_I_C = std::vector<real_type>(shared->dim_I_C);
  shared->initial_I_P = std::vector<real_type>(shared->dim_I_P);
  shared->initial_N_tot = std::vector<real_type>(shared->dim_N_tot);
  shared->initial_R = std::vector<real_type>(shared->dim_R);
  shared->initial_S = std::vector<real_type>(shared->dim_S);
  internal.lambda = std::vector<real_type>(shared->dim_lambda);
  internal.n_EI = std::vector<real_type>(shared->dim_n_EI);
  internal.n_EI_A = std::vector<real_type>(shared->dim_n_EI_A);
  internal.n_EI_P = std::vector<real_type>(shared->dim_n_EI_P);
  internal.n_GD = std::vector<real_type>(shared->dim_n_GD);
  internal.n_HD = std::vector<real_type>(shared->dim_n_HD);
  internal.n_HR = std::vector<real_type>(shared->dim_n_HR);
  internal.n_Hx = std::vector<real_type>(shared->dim_n_Hx);
  internal.n_I_AR = std::vector<real_type>(shared->dim_n_I_AR);
  internal.n_I_CG = std::vector<real_type>(shared->dim_n_I_CG);
  internal.n_I_CH = std::vector<real_type>(shared->dim_n_I_CH);
  internal.n_I_CHG = std::vector<real_type>(shared->dim_n_I_CHG);
  internal.n_I_CR = std::vector<real_type>(shared->dim_n_I_CR);
  internal.n_I_Cx = std::vector<real_type>(shared->dim_n_I_Cx);
  internal.n_I_PI_C = std::vector<real_type>(shared->dim_n_I_PI_C);
  internal.n_SE = std::vector<real_type>(shared->dim_n_SE);
  internal.p_SE = std::vector<real_type>(shared->dim_p_SE);
  shared->dim_m = shared->dim_m_1 * shared->dim_m_2;
  shared->dim_s_ij = shared->dim_s_ij_1 * shared->dim_s_ij_2;
  shared->E_ini = user_get_array_fixed<real_type, 1>(user, "E_ini", shared->E_ini, {shared->dim_E_ini}, NA_REAL, NA_REAL);
  shared->I_ini = user_get_array_fixed<real_type, 1>(user, "I_ini", shared->I_ini, {shared->dim_I_ini}, NA_REAL, NA_REAL);
  for (int i = 1; i <= shared->dim_D; ++i) {
    shared->initial_D[i - 1] = 0;
  }
  for (int i = 1; i <= shared->dim_G; ++i) {
    shared->initial_G[i - 1] = 0;
  }
  for (int i = 1; i <= shared->dim_H; ++i) {
    shared->initial_H[i - 1] = 0;
  }
  for (int i = 1; i <= shared->dim_I_A; ++i) {
    shared->initial_I_A[i - 1] = 0;
  }
  for (int i = 1; i <= shared->dim_I_P; ++i) {
    shared->initial_I_P[i - 1] = 0;
  }
  for (int i = 1; i <= shared->dim_R; ++i) {
    shared->initial_R[i - 1] = 0;
  }
  shared->offset_variable_D = shared->dim_E + shared->dim_G + shared->dim_H + shared->dim_I_A + shared->dim_I_C + shared->dim_I_P + shared->dim_R + shared->dim_S + 13;
  shared->offset_variable_E = shared->dim_S + 13;
  shared->offset_variable_G = shared->dim_E + shared->dim_H + shared->dim_I_A + shared->dim_I_C + shared->dim_I_P + shared->dim_R + shared->dim_S + 13;
  shared->offset_variable_H = shared->dim_E + shared->dim_I_A + shared->dim_I_C + shared->dim_I_P + shared->dim_R + shared->dim_S + 13;
  shared->offset_variable_I_A = shared->dim_E + shared->dim_I_P + shared->dim_S + 13;
  shared->offset_variable_I_C = shared->dim_E + shared->dim_I_A + shared->dim_I_P + shared->dim_S + 13;
  shared->offset_variable_I_P = shared->dim_E + shared->dim_S + 13;
  shared->offset_variable_N_tot = shared->dim_D + shared->dim_E + shared->dim_G + shared->dim_H + shared->dim_I_A + shared->dim_I_C + shared->dim_I_P + shared->dim_R + shared->dim_S + 13;
  shared->offset_variable_R = shared->dim_E + shared->dim_I_A + shared->dim_I_C + shared->dim_I_P + shared->dim_S + 13;
  shared->p_C = user_get_array_fixed<real_type, 1>(user, "p_C", shared->p_C, {shared->dim_p_C}, NA_REAL, NA_REAL);
  shared->p_D = user_get_array_fixed<real_type, 1>(user, "p_D", shared->p_D, {shared->dim_p_D}, NA_REAL, NA_REAL);
  shared->p_G = user_get_array_fixed<real_type, 1>(user, "p_G", shared->p_G, {shared->dim_p_G}, NA_REAL, NA_REAL);
  shared->p_H = user_get_array_fixed<real_type, 1>(user, "p_H", shared->p_H, {shared->dim_p_H}, NA_REAL, NA_REAL);
  shared->S_ini = user_get_array_fixed<real_type, 1>(user, "S_ini", shared->S_ini, {shared->dim_S_ini}, NA_REAL, NA_REAL);
  internal.s_ij = std::vector<real_type>(shared->dim_s_ij);
  for (int i = 1; i <= shared->dim_E; ++i) {
    shared->initial_E[i - 1] = shared->E_ini[i - 1];
  }
  for (int i = 1; i <= shared->dim_I_C; ++i) {
    shared->initial_I_C[i - 1] = shared->I_ini[i - 1];
  }
  for (int i = 1; i <= shared->dim_N_tot; ++i) {
    shared->initial_N_tot[i - 1] = shared->S_ini[i - 1] + shared->E_ini[i - 1] + shared->I_ini[i - 1];
  }
  for (int i = 1; i <= shared->dim_S; ++i) {
    shared->initial_S[i - 1] = shared->S_ini[i - 1];
  }
  shared->m = user_get_array_fixed<real_type, 2>(user, "m", shared->m, {shared->dim_m_1, shared->dim_m_2}, NA_REAL, NA_REAL);
  return dust::pars_type<seirhdage>(shared, internal);
}
template <>
cpp11::sexp dust_info<seirhdage>(const dust::pars_type<seirhdage>& pars) {
  const std::shared_ptr<const seirhdage::shared_type> shared = pars.shared;
  cpp11::writable::strings nms({"time", "H_inc", "D_inc", "H_inc_0_39", "H_inc_40_49", "H_inc_50_59", "H_inc_60_69", "H_inc_70_plus", "D_inc_0_39", "D_inc_40_49", "D_inc_50_59", "D_inc_60_69", "D_inc_70_plus", "S", "E", "I_P", "I_A", "I_C", "R", "H", "G", "D", "N_tot"});
  cpp11::writable::list dim(23);
  dim[0] = cpp11::writable::integers({1});
  dim[1] = cpp11::writable::integers({1});
  dim[2] = cpp11::writable::integers({1});
  dim[3] = cpp11::writable::integers({1});
  dim[4] = cpp11::writable::integers({1});
  dim[5] = cpp11::writable::integers({1});
  dim[6] = cpp11::writable::integers({1});
  dim[7] = cpp11::writable::integers({1});
  dim[8] = cpp11::writable::integers({1});
  dim[9] = cpp11::writable::integers({1});
  dim[10] = cpp11::writable::integers({1});
  dim[11] = cpp11::writable::integers({1});
  dim[12] = cpp11::writable::integers({1});
  dim[13] = cpp11::writable::integers({shared->dim_S});
  dim[14] = cpp11::writable::integers({shared->dim_E});
  dim[15] = cpp11::writable::integers({shared->dim_I_P});
  dim[16] = cpp11::writable::integers({shared->dim_I_A});
  dim[17] = cpp11::writable::integers({shared->dim_I_C});
  dim[18] = cpp11::writable::integers({shared->dim_R});
  dim[19] = cpp11::writable::integers({shared->dim_H});
  dim[20] = cpp11::writable::integers({shared->dim_G});
  dim[21] = cpp11::writable::integers({shared->dim_D});
  dim[22] = cpp11::writable::integers({shared->dim_N_tot});
  dim.names() = nms;
  cpp11::writable::list index(23);
  index[0] = cpp11::writable::integers({1});
  index[1] = cpp11::writable::integers({2});
  index[2] = cpp11::writable::integers({3});
  index[3] = cpp11::writable::integers({4});
  index[4] = cpp11::writable::integers({5});
  index[5] = cpp11::writable::integers({6});
  index[6] = cpp11::writable::integers({7});
  index[7] = cpp11::writable::integers({8});
  index[8] = cpp11::writable::integers({9});
  index[9] = cpp11::writable::integers({10});
  index[10] = cpp11::writable::integers({11});
  index[11] = cpp11::writable::integers({12});
  index[12] = cpp11::writable::integers({13});
  index[13] = integer_sequence(14, shared->dim_S);
  index[14] = integer_sequence(shared->offset_variable_E + 1, shared->dim_E);
  index[15] = integer_sequence(shared->offset_variable_I_P + 1, shared->dim_I_P);
  index[16] = integer_sequence(shared->offset_variable_I_A + 1, shared->dim_I_A);
  index[17] = integer_sequence(shared->offset_variable_I_C + 1, shared->dim_I_C);
  index[18] = integer_sequence(shared->offset_variable_R + 1, shared->dim_R);
  index[19] = integer_sequence(shared->offset_variable_H + 1, shared->dim_H);
  index[20] = integer_sequence(shared->offset_variable_G + 1, shared->dim_G);
  index[21] = integer_sequence(shared->offset_variable_D + 1, shared->dim_D);
  index[22] = integer_sequence(shared->offset_variable_N_tot + 1, shared->dim_N_tot);
  index.names() = nms;
  size_t len = shared->offset_variable_N_tot + shared->dim_N_tot;
  using namespace cpp11::literals;
  return cpp11::writable::list({
           "dim"_nm = dim,
           "len"_nm = len,
           "index"_nm = index});
}
}

cpp11::sexp dust_seirhdage_gpu_info() {
  return dust::gpu::r::gpu_info();
}
using model_cpu = dust::dust_cpu<seirhdage>;

cpp11::sexp dust_cpu_seirhdage_capabilities() {
  return dust::r::dust_capabilities<model_cpu>();
}

SEXP dust_cpu_seirhdage_alloc(cpp11::list r_pars, bool pars_multi, cpp11::sexp r_time,
                             cpp11::sexp r_n_particles, int n_threads,
                             cpp11::sexp r_seed, bool deterministic,
                             cpp11::sexp gpu_config, cpp11::sexp ode_control) {
  return dust::r::dust_cpu_alloc<seirhdage>(r_pars, pars_multi, r_time, r_n_particles,
                                        n_threads, r_seed, deterministic,
                                        gpu_config, ode_control);
}

SEXP dust_cpu_seirhdage_run(SEXP ptr, cpp11::sexp r_time_end) {
  return dust::r::dust_run<model_cpu>(ptr, r_time_end);
}

SEXP dust_cpu_seirhdage_simulate(SEXP ptr, cpp11::sexp r_time_end) {
  return dust::r::dust_simulate<model_cpu>(ptr, r_time_end);
}

SEXP dust_cpu_seirhdage_run_adjoint(SEXP ptr) {
  return dust::r::dust_run_adjoint<model_cpu>(ptr);
}

SEXP dust_cpu_seirhdage_set_index(SEXP ptr, cpp11::sexp r_index) {
  dust::r::dust_set_index<model_cpu>(ptr, r_index);
  return R_NilValue;
}

SEXP dust_cpu_seirhdage_update_state(SEXP ptr, SEXP r_pars, SEXP r_state,
                                           SEXP r_time, SEXP r_set_initial_state, SEXP index, SEXP reset_step_size) {
  return dust::r::dust_update_state<model_cpu>(ptr, r_pars, r_state, r_time,
                                                      r_set_initial_state, index, reset_step_size);
}

SEXP dust_cpu_seirhdage_state(SEXP ptr, SEXP r_index) {
  return dust::r::dust_state<model_cpu>(ptr, r_index);
}

SEXP dust_cpu_seirhdage_time(SEXP ptr) {
  return dust::r::dust_time<model_cpu>(ptr);
}

void dust_cpu_seirhdage_reorder(SEXP ptr, cpp11::sexp r_index) {
  return dust::r::dust_reorder<model_cpu>(ptr, r_index);
}

SEXP dust_cpu_seirhdage_resample(SEXP ptr, cpp11::doubles r_weights) {
  return dust::r::dust_resample<model_cpu>(ptr, r_weights);
}

SEXP dust_cpu_seirhdage_rng_state(SEXP ptr, bool first_only, bool last_only) {
  return dust::r::dust_rng_state<model_cpu>(ptr, first_only, last_only);
}

SEXP dust_cpu_seirhdage_set_rng_state(SEXP ptr, cpp11::raws rng_state) {
  dust::r::dust_set_rng_state<model_cpu>(ptr, rng_state);
  return R_NilValue;
}

SEXP dust_cpu_seirhdage_set_data(SEXP ptr, cpp11::list data,
                                       bool shared) {
  dust::r::dust_set_data<model_cpu>(ptr, data, shared);
  return R_NilValue;
}

SEXP dust_cpu_seirhdage_compare_data(SEXP ptr) {
  return dust::r::dust_compare_data<model_cpu>(ptr);
}

SEXP dust_cpu_seirhdage_filter(SEXP ptr, SEXP time_end,
                                     bool save_trajectories,
                                     cpp11::sexp time_snapshot,
                                     cpp11::sexp min_log_likelihood) {
  return dust::r::dust_filter<model_cpu>(ptr, time_end,
                                                save_trajectories,
                                                time_snapshot,
                                                min_log_likelihood);
}

void dust_cpu_seirhdage_set_n_threads(SEXP ptr, int n_threads) {
  return dust::r::dust_set_n_threads<model_cpu>(ptr, n_threads);
}

int dust_cpu_seirhdage_n_state(SEXP ptr) {
  return dust::r::dust_n_state<model_cpu>(ptr);
}

void dust_cpu_seirhdage_set_stochastic_schedule(SEXP ptr, SEXP time) {
  dust::r::dust_set_stochastic_schedule<model_cpu>(ptr, time);
}

SEXP dust_cpu_seirhdage_ode_statistics(SEXP ptr) {
  return dust::r::dust_ode_statistics<model_cpu>(ptr);
}
